version: '3.8'
services:
  nginx:
    build: ./docker/nginx
    container_name: nginx
    restart: always
    volumes:
      - ./docker/nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/config/app.vhost:/etc/nginx/conf.d/app.vhost
      - ./docker/nginx/logs:/var/log/nginx
      - ./src/:/var/www/html
    networks:
      - nginx
    depends_on:
      - 'php'
    ports:
      - '9090:80'

  php:
    build: ./docker/php8.1
    container_name: php
    restart: always
    networks:
      - nginx
      - db
    depends_on:
      - postgres
    volumes:
      - ./src/:/var/www/html

  postgres:
    build: ./docker/postgres
    container_name: postgres
    restart: always
    networks:
        - db
    ports:
        - '6543:5432'
    environment:
        - POSTGRES_PASSWORD=postgres

networks:
  nginx:
  db: