FROM php:8.1-fpm

RUN apt-get update \
    && apt-get install -y \
        zlib1g-dev \
        libicu-dev \
        libpq-dev \
        libmcrypt-dev \
        libpng-dev \
        libzip-dev \
        zip \
        g++ \
        git \
        libxml2-dev \
        vim \
    && docker-php-ext-configure intl \
    && docker-php-ext-configure soap --enable-soap \
    && docker-php-ext-install intl zip gd opcache pdo_pgsql soap \
    && docker-php-ext-install pgsql \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
    && chmod +x /usr/local/bin/composer